version: '3.8'

services:
  redis:
    image: redis
    container_name: redis
    networks:
      - jp2anki
    ports:
      - "6379:6379"
    restart: unless-stopped

  celery:
    image: jp2anki:test
    command: celery -A api:celery_app worker
    networks:
      - jp2anki
    depends_on:
      - redis

  app:
    image: jp2anki:test
    networks:
      - jp2anki
    ports:
      - "8000:8000"
    depends_on:
      - redis
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx
    networks:
      - jp2anki
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    restart: unless-stopped

networks:
  jp2anki:
    driver: bridge
