version: '3.8'

services:
  flask:
    build:
      context: .
      dockerfile: docker_file_backend
    ports:
      - "5000:5000"
    depends_on:
      - redis

  celery:
    build:
      context: .
      dockerfile: docker_file_celery
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
